questions =  [
   
    {"id": 0, "question": "Some people might say I’m boring.", "effects": {"left": 1}},
    {"id": 1, "question": "If you have a problem with me, tell it to my face.", "effects": {"right": 1}},
    {"id": 2, "question": "I work well as part of a team.", "effects": {"right": 1}},
    {"id": 3, "question": "I speak before I think", "effects": {"right": 1}},
    {"id": 4, "question": "People tire me out.", "effects": {"left": 1}},
    {"id": 5, "question": "I almost never pick up when my cell phone rings.", "effects": {"left": 1}},
    {"id": 6, "question": "I make people laugh", "effects": {"right": 1}},
    {"id": 7, "question": "I can text, play a video game and help my sibling at the same time.", "effects": {"right": 1}},
    {"id": 8, "question": "My dream weekend? Just kicking back with nothing to do.", "effects": {"right": -1}},
    {"id": 9, "question": "I'd rather hang out with one friend than going out to a mall with a group.", "effects": {"right": -1}},
    {"id": 10, "question": "I hate it when people look over my shoulder when I'm doing something", "effects": {"right": -1}},
    {"id": 11, "question": "I hate writing in a journal", "effects": {"right": 1}},
    {"id": 12, "question": "I hate to be alone", "effects": {"right": 1}},
    {"id": 13, "question": "I'm going to be rich and famous some day, seriously.", "effects": {"right": 1}},
    {"id": 14, "question": "I don't say much unless I really know you.", "effects": {"right": -1}},
    {"id": 15, "question": "I'm a good listener", "effects": {"left": 1}},
    {"id": 16, "question": "When it's my birthday, please don't make a big deal out of it", "effects": {"left": 1}},
    {"id": 17, "question": "I really really do not like homework.", "effects": {"right": 1}},
    {"id": 18, "question": "I focus on one thing at a time", "effects": {"left": 1}},
    {"id": 19, "question": "I'm a thrill seeker", "effects": {"right": 1}},
    {"id": 20, "question": "Things usually turn out the best for me.", "effects": {"auth": 2}},
    {"id": 21, "question": "My future is so bright! I got to wear shades.", "effects": {"auth": 2}},
    {"id": 22, "question": "When all is said and done, I expect more good things to happen than bad things.", "effects": {"auth": 2}},
    {"id": 23, "question": "If something can go wrong, it will!.", "effects": {"auth": -2}},
    {"id": 24, "question": "I hardly every count on things going my way.", "effects": {"auth": -2}},
    {"id": 25, "question": "I do not get my hopes up.", "effects": {"auth": -2}},
